### ISSUE TITLE
GitHub Actions should be referenced by SHA not tag

### ISSUE THREAD

**Issue by stevehipwell** [chainguard-dev/actions#208]
Just like how container images should be referenced by digest, GitHub actions should be referenced by SHA and not tag. Dependabot can handle this pattern including keeping the tag used next to the SHA as a comment.

```yaml
jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
```
