### ISSUE TITLE
Configured but not signing

### ISSUE THREAD

**Issue by cjhelloletsgo** [chainguard-dev/actions#469]
Is there an extra step I still have to configure to get my commits to be signed?

I am getting an error because my commit is not signed:
```
remote: - Commits must have verified signatures.        
```

Here is my yaml file:
```yaml
name: Ruff Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    permissions:
      contents: write
      id-token: write # Enable OIDC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check . --ignore F841 --fix

      - name: Format code
        run: ruff format

      - uses: chainguard-dev/actions/setup-gitsign@main

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style fixes by ruff"
          # commit_options: "-S"
```
